[package]
name = "migrations"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
tokio = { workspace = true }
dotenv = { workspace = true }
